 services:
   app:
     build: .
     ports:
       - "80:80"
       - "443:443"
       - "443:443/udp"
     restart: always
     volumes:
       - caddy_data:/data
       - caddy_config:/config
     environment:
       APP_ENV: production
       APP_DEBUG: true
       APP_KEY: base64:+pZsUWwY5+Fq1jH62fAZ0g3VacLL44+IwYCkrmqRwY8=
       OCTANE_SERVER: frankenphp
       APP_DATAKU: dataku
       DB_CONNECTION: mysql
       DB_HOST: 146.190.96.159
       DB_PORT: 3306
       DB_DATABASE: semesta
       DB_USERNAME: semesta
       DB_PASSWORD: cbw8i@22d2

 volumes:
   caddy_data:
   caddy_config:


