services:
  app:
    build: .
    entrypoint: php artisan octane:frankenphp --workers=1 --max-requests=1 --host=0.0.0.0 --port=80
    ports:
      - "80:80"
    volumes:
      - .:/app
    environment:
      APP_ENV: production
      APP_DEBUG: false
      APP_KEY: base64:+pZsUWwY5+Fq1jH62fAZ0g3VacLL44+IwYCkrmqRwY8=
