 services:
   app:
     build: .
     ports:
       - "80:80"
       - "443:443"
       - "443:443/udp"
     restart: always
     volumes:
       - caddy_data:/data
       - caddy_config:/config
     environment:
       APP_ENV: production
       APP_DEBUG: false
       APP_KEY: base64:+pZsUWwY5+Fq1jH62fAZ0g3VacLL44+IwYCkrmqRwY8=
       OCTANE_SERVER: frankenphp
       APP_DATAKU: dataku

 volumes:
   caddy_data:
   caddy_config:


